=== RaamyAfifi/dataprocessing_2021-2022/src/main/java/dataprocessing_2022/raamy/json/jsonSchema_profile_dataprocessing.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://github.com/RaamyAfifi/dataprocessing_2021-2022",
	"title": "Profile",
	"description": "A profile",
	"type": "object",
	"properties": {
		"profile":{
			"description": "Unique name for a specific profile",
			"type": "String"
		},
		"gender":{
			"description": "Gender of a user. (Man, Women, Neutral)",
			"type": "String"
		},
		"birthday":{
			"description": "Birthday of a user.",
			"type": "String"
		},
		"favorites_anime":{
			"description": "Contains the favorite animes of a user.",
			"type": "String"
		},
		"link":{
			"description": "link of a specific user.",
			"type": "String"
		}
	}
}

=== RaamyAfifi/dataprocessing_2021-2022/src/main/java/dataprocessing_2022/raamy/json/json_profile_dataprocessing.json
{
    "profile": "Palmero",
    "gender": "Neutral",
    "birthday": "2 0ct, 2010",
    "link": "google.com",
    "favorites_anime": [
      {
        "uid": 2.0,
        "title": "One Piece",
        "genre": ["Super Natural", "Magic"],
        "aired": "2 oct, 2010",
        "episodes": 48.0,
        "members": 483.0,
        "score": 8
      }
    ]
  }
