=== RaamyAfifi/dataprocessing_2021-2022/src/main/java/dataprocessing_2022/raamy/json/jsonSchema_review_dataprocessing.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://github.com/RaamyAfifi/dataprocessing_2021-2022",
	"title": "Review",
	"description": "review of an anime",
	"type": "object",
	"properties": {
		"uid":{
			"description": "Unique numer for a specific anime",
			"type": "int"
		},
		"profile":{
			"description": "Name of a user",
			"type": "string"
		},
		"anime_uid":{
			"description": "uid of an anime",
			"type": "int"
		},
		"score":{
			"description": "score of a anime given by a user",
			"type": "int"
		},
		"link":{
			"description": "link of a specific review of a user.",
			"type": "String"
		}
	}
}

=== RaamyAfifi/dataprocessing_2021-2022/src/main/java/dataprocessing_2022/raamy/json/json_review_dataprocessing.json
{
    "uid": 2,
    "profile": "RubberDucky",
    "anime_uid": {
      "uid": 7,
      "title": "Sword Art Online",
      "genre": ["Magic", "Romance"],
      "aired": "3 sep, 2016",
      "episodes": 50,
      "members": 51265,
      "score": 9.5
    },
    "score": 10.0,
    "link": "google.com"
  }
